//
//  FruitsAndBerriesModels.swift
//  iOS-Test
//

enum FruitsAndBerriesModels {
    // Models for "load (list)" use case
    struct Load {
        // Request is passed to Interactor
        struct Request {
            let item: String
        }
        // Response is passed from Interactor to Presenter
        struct Response {
            let products: Models.ProductsModel
        }
        // View model is generated by Presenter and passed to View
        struct ViewModel {
            let products: Models.ProductsModel
            var isProductsListEmpty: Bool {
                products.items.count == 0
            }
        }
    }
    
    struct LoadDetails {
        // Request is passed to Interactor
        struct Request {
            let productId: String
        }
        // Response is passed from Interactor to Presenter
        struct Response {
            let description: Models.DescriptionModel
        }
        // View model is generated by Presenter and passed to View
        struct ViewModel {
            let description: Models.DescriptionModel
        }
    }
}
